stages:          # List of stages for jobs, and their order of execution
  - release

release_job:
  stage: release
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  rules:
    - if: $CI_COMMIT_TAG                 # Run this job when a tag is created
  script:
    - echo "running release_job"
  release:                               # See https://docs.gitlab.com/ee/ci/yaml/#release for available properties
    tag_name: '$CI_COMMIT_TAG'
    description: '$CI_COMMIT_TAG'
    steps:
     - name: Upload Release Asset
     uses: actions/upload-release-asset@v1
        with:
          asset_path: ./android/app/release/app-release.apk
          asset_name: APK

